Set right order of grouped menu entries
bolt/bolt pull request #7219
Opened 2017-11-28 17:49 UTC by JarJak

Previously, all grouped menu entries were put at the bottom of menu (as "other" menu).

Now they can be mixed with non-grouped entries with proper order as defined in contenttypes.yml.

Some tests can be added later (or updated if some of them would fail).

Discussed on Slack with @bobdenotter

2017-11-28 17:53 UTC, GwendolenLynch requested changes
Update tests please

2017-11-29 04:18 UTC, GwendolenLynch requested changes
Changed logic still not covered in tests.

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +            return;
Dead code, you check this above.

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +            if ($contentType['show_in_menu'] === true) {
`$this->contentTypes` is a recursive `Bag`, ergo `$contentType` is a `Bag`, use the getter please.

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +            } else {
Remove the `else` and add a `continue;` above

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +        }
`$key = $contentType->get('show_in_menu') ?: 'other;`

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +    private function prepareGroupedMenu(MenuEntry $contentRoot, Bag $contentType)
Docblock

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +            if ($contentType['show_in_menu'] === true) {
Also, you're looking for the exception to the logical flow, it would be cleaner to flip the test, i.e. `!== true`

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Builder/AdminContent.php
> +    private function prepareGroupedMenu(MenuEntry $contentRoot, Bag $contentType)
This is an "add" not a "prepare", and move below the `addContentType()` method

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Resolver/RecentlyEdited.php
> +                foreach ($contentMenu->children() as $name => $contentMenu) {
`$name` and `$contentMenu` are already in use … this is really bad practice.

2017-11-29 04:18 UTC, GawainLynch commented on src/Menu/Resolver/RecentlyEdited.php
> +                    }
Nesting is too deep, restructure and simplify the logic, please.

2017-12-04 10:28 UTC, GwendolenLynch submitted a review, later dismissed

2017-12-04 15:27 UTC, GwendolenLynch approved these changes
Thanks mate, and extra thanks for the unit tests :+1:

2017-12-04 15:28 UTC, merged

2017-12-04 15:41 UTC, bobdenotter commented
Yay, teamwork! Happy we landed this improvement! 👏