Bump version of `paragonie/random_compat` to `^2.0`.
bolt/bolt pull request #7359
Opened 2018-02-28 19:28 UTC by bobdenotter

Fixes #7358.

🐵  Tested and found to be working on PHP 5.5.38, 5.6.31, 7.0.22 and 7.1.6 and 7.21.

2018-02-28 20:16 UTC, SahAssar commented
We should probably be clear in the docs that for windows we will require php-mcrypt from now on (since random-compat will fail otherwise.)

2018-03-01 03:17 UTC, GwendolenLynch requested changes

2018-03-01 03:17 UTC, GawainLynch commented on composer.json
> +        "paragonie/random_compat": "^2.0",
If we go this way, this line can just be dropped … You added it in #5366 to version lock.

2018-03-01 03:21 UTC, GawainLynch commented
OK, so we don't have a choice in this one, it is a security win IMHO. But the losers are PHP5 users on shared hosts, as it breaks Bolt 100% of the time if `open_basedir` is in effect … so people using incompetent shared hosts lose support when this is merged:

```
file_exists(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s)
```

2018-03-01 08:22 UTC, bobdenotter commented
Hmm.. We should of course make changes, if they're dictated by security recommendations, but I'm not too keen on getting (perhaps) an increase on us having to explain to people "Yes, it was in the notes. No, it's not our fault, it's better. Yes, you should contact your host, even if they live under a rock." 

🤔 💭

2018-03-01 10:24 UTC, GwendolenLynch approved these changes

2018-03-01 10:24 UTC, merged