Add feature to fetch placeholder images from remote URLs
bolt/bolt pull request #7368
Opened 2018-03-08 18:36 UTC by bobdenotter

Tired of the same random placeholder images? Too few kittens? This PR will allow you to add new placeholder images to your contenttypes, when using the "add loripsum content": 

![screen shot 2018-03-08 at 19 27 36](https://user-images.githubusercontent.com/1833361/37169324-e67a57e2-2307-11e8-8495-4727df285b7a.png)

```
    fields:
        title:
            type: text
            class: large
            group: content
        …
        image:
            type: image
            group: media
            placeholder: https://source.unsplash.com/1600x900/?nature,water/__random__
```

or `https://source.unsplash.com/1600x900/?kitten/__random__` for more kittens. 

Should be trivial to make work with other placeholder services, like pexels, visualhunt or placekitten. Or we could even write our own, if we don't want to be reliant on a 3rd party service.

2018-03-09 10:50 UTC, GwendolenLynch requested changes

2018-03-09 10:50 UTC, GawainLynch commented on src/Storage/Database/Prefill/RecordContentGenerator.php
> +            } catch (\Exception $e) {
This is not a good idea, you don't want to catch everything silently, it makes it *extremely* hard to debug.

So …
- `getImage()`  can throw a `GuzzleHttp\Exception\RequestException` if there is a problem handling the call
- `write()` will throw a `Bolt\Filesystem\Exception\FileExistsException` that can be avoided by calling `put()`

If other exceptions are being thrown, we want to know about them as something else is fundamentally wrong.

2018-03-09 10:50 UTC, GawainLynch commented on src/Storage/Database/Prefill/RecordContentGenerator.php
> +                return [$pathKey => $filename, 'title' => 'placeholder', 'alt' => 'placeholder'];
PSR-2 requires a newline before then `return`

2018-03-09 10:50 UTC, GawainLynch commented on src/Storage/Database/Prefill/ApiClient.php
> +        return $this->client->get($url, ['timeout' => 10])->getBody();
PSR-2 requires a newline before then return

2018-03-09 10:50 UTC, GawainLynch commented on src/Storage/Database/Prefill/RecordContentGenerator.php
>          $value = null;
While I am nagging, drop the newline before this one :stuck_out_tongue_winking_eye:

2018-03-09 10:50 UTC, GawainLynch commented on src/Storage/Database/Prefill/ApiClient.php
> +     * @return StreamInterface
Needs a `use Psr\Http\Message\StreamInterface;` added

2018-03-09 10:50 UTC, GawainLynch commented on src/Storage/Database/Prefill/RecordContentGenerator.php
> +    private function getRandomImage($type, $placeholder = null)
`$placeholder` doesn't need a default, and does need a `@param string|null $placeholder` in the docblock

2018-03-10 14:46 UTC, bobdenotter commented on src/Storage/Database/Prefill/ApiClient.php
> +     * @return StreamInterface
Added.

2018-03-14 04:39 UTC, GwendolenLynch approved these changes

2018-03-14 05:07 UTC, merged