New Feature: Collapsible Blocks and Repeaters
bolt/bolt pull request #7443
Opened 2018-04-15 16:13 UTC by bobdenotter

Builds on / replaces PR #7441 by @binarykiwi. 

Changes: 

 - Clean up the UI a bit. 
 - Apply same logic to Repeaters, not just Blocks
 - Simplify logic a bit: Only use `collapsible: true` (default) and `collapsible: false`.

2018-04-15 17:44 UTC, jadwigo commented
I would move the delete button to a separate group..  the delete button is an irreversible action and should be visually different and harder to access reversible actions in the UI

2018-04-15 17:46 UTC, jadwigo requested changes
Separate the delete button so reversible and irreversible actions are split

2018-04-16 06:14 UTC, bobdenotter commented
Updated. 

![screen shot 2018-04-16 at 08 13 47](https://user-images.githubusercontent.com/1833361/38792616-2ec05376-414e-11e8-9400-8b27168919c4.png)

2018-04-16 06:57 UTC, jadwigo approved these changes

2018-04-16 07:15 UTC, merged