[3.6][WIP] Ignore default value alteration for MySQL TEXT and BLOB types
bolt/bolt pull request #7477
Opened 2018-05-10 12:49 UTC by JarJak

**Steps to reproduce:**
1. Create field with textarea type
2. Update database
3. Add default value to this type
4. Run database check and update

**Expected result:**
Database is up to date

**Actual result:**
Even after database update there is message "Invalid column X".
"Show proposed alterations" does not generate any SQL.

See https://github.com/doctrine/dbal/pull/514

2018-05-10 13:19 UTC, GwendolenLynch requested changes

2018-05-10 13:19 UTC, GwendolenLynch commented on src/Storage/Database/Schema/Comparison/MySql.php
> +        }
All this is not needed and would be bi-directional.

Assuming that this is valid to ignore, and I don't think it is for all versions of that crap platform you'd just want:
```php
    protected function setIgnoredChanges()
    {
        $this->ignoredChanges[] = new IgnoredChange('changedColumns', 'type', 'text', 'blob');
    }
```

Also, it needs to be considered if this affects DBAL 2.5, 2.6 & 2.7, MySQL 5.5, 5.6, 5.7, 8.0, 9.0, and MariaDB =< 10.1, 10.2, 10.3.

2018-05-10 13:51 UTC, JarJak commented on src/Storage/Database/Schema/Comparison/MySql.php
> +        }
This is not about directions. Bug is not caused by column type change, just both TEXT and BLOB types are affected.

It affects DBAL >= 2.5 and probably every version of MySQL / MariaDB.

2018-05-10 13:53 UTC, GawainLynch commented on src/Storage/Database/Schema/Comparison/MySql.php
> +        }
>  Bug is not caused by column type change

Then the PR isn't valid :wink: 

> It affects DBAL >= 2.5 and probably every version of MySQL / MariaDB.

Have you tested this on all combinations, as I am willing to bet a beer that you're wrong.

2018-05-10 14:08 UTC, JarJak commented on src/Storage/Database/Schema/Comparison/MySql.php
> +        }
Starting from MariaDB 10.2.1, BLOB and TEXT columns can have a DEFAULT value. However DBAL has separate Driver for this version of MariaDB: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/MariaDb1027Platform.php
Mysql is affected from 5.5 up to 8.0. I can't check it for 9.0 as this version is not yet released.

2018-05-10 14:12 UTC, GawainLynch commented on src/Storage/Database/Schema/Comparison/MySql.php
> +        }
>  I can't check it for 9.0 as this version is not yet released.

Ah, no stress on that one. I thought it had gone GA recently but happily, I am wrong. :smile: 

> Starting from MariaDB 10.2.1, BLOB and TEXT columns can have a DEFAULT value. However DBAL has separate Driver for this version of MariaDB: 

Yeah, and this is part of the living disaster that probably makes it unworkable.

Would a Bundle on a port of this work for you needs though? https://github.com/bolt/bolt-extension-compat-mariadb

2018-06-08 20:14 UTC, JarJak commented on src/Storage/Database/Schema/Comparison/MySql.php
> +        }
@GawainLynch the extension you provided disables all default checks, this is not needed nor good solution. Here's why:
- this is not only about MariaDB 10.2.1+ but for MySQL 5.5+ too
- only TEXT column type is affected (I don't think Bolt uses BLOB anywhere)

2018-09-12 08:27 UTC, JarJak commented
updated with assert()

2018-11-11 10:38 UTC, bobdenotter commented
@jarjak Is this still valid for current 3.6?

2018-11-11 11:02 UTC, JarJak commented
Yes

Niedz., 11 lis 2018, 11:38: Bob den Otter <notifications@github.com>
napisał(a):

> @JarJak <https://github.com/JarJak> Is this still valid for current 3.6?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bolt/bolt/pull/7477#issuecomment-437659218>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AEwC8ri23-bI_hwuja9mtZ2SDbAKbfK_ks5ut_4xgaJpZM4T51zw>
> .
>

2019-01-04 13:35 UTC, bobdenotter approved these changes
👍

2019-01-04 13:35 UTC, merged