Excerpt strip fields.
bolt/bolt pull request #7759
Opened 2019-03-08 15:27 UTC by artggd

Fixes #7758

Allow to strip unwanted fields out of the excerpt by adding a fourth argument to Excerpt and related runtime methods.

Doc update on its way.

2019-03-08 15:43 UTC, JarJak commented
Could add a test for it?

2019-03-08 15:51 UTC, artggd commented
Sure thing, fixing checks first :)

By the way, the CI fails because of a bad call of `content|excerpt` in `bolt/_base/_listing.twig` where `content.excerpt` should've been call.

`content.excerpt` and `content|excerpt` don't take the same arguments (`.excerpt` has `$includeTitle` as second argument). This didn't break in the past because the last argument was simply ignored. Now that I added another one, type hinting breaks.

Although this PR doesn't break BC, I'm afraid it could be dangerous in the end...

2019-03-10 15:03 UTC, bobdenotter submitted a review, later dismissed
> content.excerpt and content|excerpt don't take the same arguments (.excerpt has $includeTitle as second argument). 

This is because the `.excerpt` works on a `content` object only, but `|excerpt` is a generic filter, that works on strings, arrays or content-like objects. 

> Although this PR doesn't break BC, I'm afraid it could be dangerous in the end...

It seems to work fine, and I don't spot immediate issues.. 👍 

Are you worried about merging it in?

2019-03-10 15:40 UTC, artggd commented
Well, I understand the difference between `.excerpt` and `|excerpt` but it's easily confusable. Taking for proof there was a miscall in Bolt's core.

I reckon there's might be quite an amount of projects miscalling `.excerpt` and passing the same args as `|excerpt`. Those will break on their next `composer up`.

Though I really need this feature, I'd say the merge could wait for the next major release. Unless you have any way of measuring the risks and/or are willing to accept it.

Your call ;)

2019-03-10 15:48 UTC, artggd commented
Or, maybe we could remove the type hint of `$stripFields` so that if a fourth arg is wrongly passed to `.excerpt` (miscall of `$focus` (string)) it won't break. But I'm not fond of this option, hacky...

2019-03-10 16:43 UTC, JarJak commented
Actually $stripFields param could be added only to Content method, because it is valid only with Content context.
I would leave excerpt filter as-is.

Docs needs an update, can you provide separate PR for them @artggd ?

2019-03-10 17:58 UTC, artggd commented
The filter is very versatile and is valid for `string`, `Content` or `array`. It still makes sense to have `$stripFields` in both filter and Content method IMO. 
The issue would remain anyway, it breaks when Content method is called with the filter params, not the other way round. Which is probably the most common case.

I'm thinking removing type hinting could actually be an ok solution with proper type control in the filter. It would also add some flexibility, allowing for usage of the filter like so 
```TWIG
{{ stuff|excerpt(stripFields="strip out those fields") }}
```
 Just need to explode `$stripFields` when it's a string.

If you guys are happy with this option, I'll make the update and add a couple of tests.

@JarJak I did provide a PR for doc update 😉👉 https://github.com/bolt/docs/pull/953

2019-03-10 18:19 UTC, JarJak commented
>The filter is very versatile and is valid for string, Content or array. 

Yes, you can use filter on content, but this more like extra feature than normal usage. And since $stripFields makes sense only in Content context, I would leave this parameter only in Content method.

2019-03-10 18:28 UTC, JarJak submitted a review, later dismissed

2019-03-10 18:34 UTC, JarJak commented
Oh, and I'm not happy with
```
{{ stuff|excerpt(stripFields="strip out those fields") }}
```
As an option. It doesn't make sense to me to allow such way of using this feature.

2019-03-10 18:34 UTC, artggd commented
Agreed, if we wan't to restrict $stripFields on Content only, then let's move out all the related logic to Content and leave the filter to only work with strings.  It'd be way more consistent.

What about merging this as a transitional step and add keep strict typing for next major?

2019-03-10 18:38 UTC, artggd commented
> Oh, and I'm not happy with
> 
> ```
> {{ stuff|excerpt(stripFields="strip out those fields") }}
> ```
> As an option. It doesn't make sense to me to allow such way of using this feature.

Then $stripFields could simply be ignored if string and raise a warning (rather than a 500)

2019-03-10 18:40 UTC, JarJak commented
@artggd in next major (Bolt 4) we made a slightly different approach. Fields that are allowed in Excerpt must implement Excertable interface. Look for usages of https://github.com/bolt/four/blob/master/src/Entity/Field/Excerptable.php and as always, PRs are more than welcome!

2019-03-10 19:39 UTC, artggd commented
@JarJak This sounds very nice 🙂
Although I can see field values are stored in a json column, I don't know how you're going to achieve search without pulling out heavy indexing!
Digressing, this is not the place to discuss this but I'd be more than happy to help. I've had similar issue in the past and solved it with a different approach but I guess Bolt 4's architecture is already thought and written down.

2019-03-11 09:21 UTC, JarJak commented
@artagd we are open for all ideas and we can change everything before beta :)

2019-03-11 09:44 UTC, artggd commented
@JarJak I'll catch-up with you on https://github.com/bolt/four/issues/306 when I get some time :)

Short recap of this issue, we've got 4 options left:
1. Merging as is.
1. Removing `$stripFields` type hint and raise a warning if not an array.
1. Allowing `$stripFields` on Content method only and move the Content related logic out of the filter (inducing a BC break).
1. Allowing `$stripFields` on Content method only and keep Content related logic in the filter.

My personal fav being number 2

2019-03-11 13:00 UTC, JarJak commented
I'm ok with either 2 or 4. @bobdenotter ?

2019-03-11 13:03 UTC, bobdenotter commented
Nr. 2 has my preference! 👍

2019-03-11 13:23 UTC, artggd commented
Sweet then, working on it 👍

2019-03-11 15:43 UTC, artggd commented
Hey so, I'm still working but I've ran into a small coding issue.

I decided to log a message rather than '@trigger_error' because trigger_error doesn't show up in the debug toolbar unless it's a deprecated call. Also, it's a pain to unit test.

Problem is, `Excerpt` is not a service so I have to duplicate the same bit of code in the callers (which are services and can access the logger).

I'm really not happy with that.

Any recommendation? How'd you achieve that in a cleaner way?

2019-03-11 15:53 UTC, JarJak commented
Normally I would just throw an Exception there.

2019-03-11 15:55 UTC, artggd commented
I would too, but that was the point Nr. 2. Not throwing an exception so it doesn't break in case of a miscall 🙂

2019-03-11 16:03 UTC, JarJak commented
Then I think we can deprecate it.

Decorating every excerpt call with logger is not an option because there can always be n+1 call in extension or user's code.

2019-03-12 09:12 UTC, JarJak requested changes

2019-03-12 09:12 UTC, JarJak commented on src/Helpers/Excerpt.php
> +        if (null === $stripFields || !is_array($stripFields)) {
default value triggers error?

2019-03-12 09:20 UTC, artggd commented on src/Helpers/Excerpt.php
> +        if (null === $stripFields || !is_array($stripFields)) {
I realize that this morning, update coming up now

2019-03-12 09:22 UTC, artggd commented
It should be ready to merge, I also added 3 tests on ContentTests.

2019-03-12 11:30 UTC, JarJak requested changes

2019-03-12 11:30 UTC, JarJak commented on src/Helpers/Excerpt.php
> +    public function getExcerpt($length = 200, $includeTitle = false, $focus = null, $stripFields = null)
just set default value of $sripFields to [] here

2019-03-12 11:31 UTC, JarJak requested changes

2019-03-12 11:31 UTC, JarJak commented on src/Helpers/Excerpt.php
> +     * @param array|null        $stripFields
remove null

2019-03-12 13:33 UTC, artggd commented
Not sure what's wrong with the CI, the tests run smooth on my machine and it seems to fail on nothing related to my last dev.

2019-03-12 16:17 UTC, JarJak approved these changes

2019-03-12 16:26 UTC, bobdenotter commented
Tests are failing, a lot of: 

```
Error: Call to undefined method Twig\TemplateWrapper::getTemplateName()
```

Looks like this is introduced in this update: https://symfony.com/blog/twig-sandbox-information-disclosure

2019-03-12 21:20 UTC, bobdenotter commented
The issue with Twig is fixed. See: https://github.com/twigphp/Twig/issues/2892

2019-03-12 21:33 UTC, artggd commented
Great! Thanks @bobdenotter

2019-03-12 21:34 UTC, bobdenotter commented
@artggd Thank _you_ for the PR! 👍

2019-03-12 21:34 UTC, merged