Fixing ternary operatorin ImageRuntime v2
bolt/bolt pull request #7832
Opened 2019-12-29 06:08 UTC by Boorj

again, as in #7805

2019-12-29 09:06 UTC, bobdenotter requested changes

2019-12-29 09:06 UTC, bobdenotter commented on src/Twig/Runtime/ImageRuntime.php
> +        if (isset($fileName['filename']) {
```suggestion
        if (isset($fileName['filename'])) {
```

2019-12-29 09:06 UTC, bobdenotter commented on src/Twig/Runtime/ImageRuntime.php
> +        if (isset($fileName['file']) {
```suggestion
        if (isset($fileName['file'])) {
```

^ Two typos

2020-02-02 18:17 UTC, Boorj commented
@bobdenotter isn't it ok now?

2020-02-03 07:54 UTC, bobdenotter approved these changes
@Boorj  Sorry, I missed that last update. Yes, looks good now! 👍

2020-02-03 07:54 UTC, merged